### ISSUE TITLE
Seeing CORS issues on API redirects

### ISSUE THREAD

**Issue by aecorredor** [aiji42/next-qs-props#126]
First off, thanks for putting this together. It worked great for us.

However, we did encounter one issue right after we added the package.

We have a vercel commerce app with Shopify as the provider, and if you look at that project there's a rewrite happening when visiting `/checkout`. It basically points that to `/api/checkout`, which performs some backend logic to make sure that the shopify checkout is created correctly, and after it does that it redirects to the external Shopify URL by doing `res.redirect(checkoutUrl)`. So, our app lives in `myshop.com`, and the `checkoutUrl` looks like `checkout.myshop.com`. 

That was all working fine until we added the `qs-props` middleware. We are now seeing the Next.js client side error page because the redirect is causing a CORS error. It seems that after adding the middleware the allow-origin header got lost, so now redirecting from `myshop.com` to `checkout.myshop.com` is being blocked by the browser.

Any ideas about what I might be missing? I tried implementing CORS in `next.config.js`, but had no luck.

**Comment by aiji42** [comment]
@aecorredor Try using the middleware [`config.matcher`](https://nextjs.org/docs/advanced-features/middleware#matching-paths) to limit the scope in which `sq-props` checks requests. In other words, do not allow the middleware to run on requests to `/checkout`. If it is the middleware or `sq-props` that is causing your problem, this should solve it.

**Comment by aecorredor** [comment]
@aiji42 I did already have a matcher that was making sure the middleware only ran for `/product/:path*`. I verified that was true with some logging. The issue still persisted. I found a work-around for now, but basically had to drop the `res.redirect` from the API route.

**Comment by aiji42** [comment]
> I found a work-around for now, but basically had to drop the res.redirect from the API route.

Does that mean that the problem was not caused by `qs-props`?

If the matcher is set correctly, this library will not be executed on `/checkout` or `/api/checkout` accesses, so it cannot cause the problem.

**Comment by aecorredor** [comment]
@aiji42 Yeah, I'm still not sure what the source of the issue is. I just know that taking out the `middleware.ts` file made things work again. Maybe it's not `qs-props` and it's just something specific to Next middleware that caused the issue. The TLDR is that with a middleware file I saw the `res.redirect` to an external URL fail with CORS issues since the `Access-Control-Allow-Origin` header was lost. Closing for now as at this point I don't think it's specific to this package.
